<?php
add_action('wp_enqueue_scripts', function() {

    
	$port = MINT_OPTIONS['port'];

    if (IS_PRODUCTION) {
		$files = MINT_OPTIONS['files'];
		
		wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			get_stylesheet_directory_uri() . '/dist/' . $files['app']['js'],
			array(),
			false,
			true
		);
		
		wp_enqueue_style( 
			'themin/app.css',
			get_stylesheet_directory_uri() . '/dist/' . $files['app']['css']
		);
		if ($vendor = $files['chunk-vendors']) {
			if ($css = $vendor['css'])
				wp_enqueue_style( 
					'themin/vendor.css',
					get_stylesheet_directory_uri() . '/dist/' . $css
				);
			if ($js = $vendor['js'])			
				wp_register_script( // the app build script generated by Webpack.
					'themint/vendor.js',
					get_stylesheet_directory_uri() . '/dist/' . $js,
					array(),
					false,
					true
				);
		}

    } else {
        wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			'http://localhost:'. $port .'/app.js',
			array(),
			false,
			true
		);

		
	}

	wp_enqueue_script('themint/app.js');
	wp_enqueue_script('themint/vendor.js');
});