<?php
add_action('wp_enqueue_scripts', function() {

    
	$port = OPTIONS['port'];

    if (IS_PRODUCTION) {
		$files = $options['files'];
		wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			THEME_ROOT . '/dist/' . $files['app']['js'],
			array(),
			false,
			true
		);
		wp_register_script( // the app build script generated by Webpack.
			'themint/vendor.js',
			THEME_ROOT . '/dist/' . $files['chunk-vendors']['js'],
			array(),
			false,
			true
		);
		wp_enqueue_style( 
			'themin/app.css',
			THEME_ROOT . '/dist/' . $files['app']['css']
		);
		wp_enqueue_style( 
			'themin/vendor.css',
			THEME_ROOT . '/dist/' . $files['chunk-vendors']['css']
		);

    } else {
        wp_register_script( // the app build script generated by Webpack.
			'themint/app.js',
			'http://localhost:'. $port .'/app.js',
			array(),
			false,
			true
		);

		
	}

	wp_enqueue_script('themint/app.js');
	wp_enqueue_script('themint/vendor.js');
});